spring.application.name=DicionarioTupiGuarani

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dicionario_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

server.port=3000
spring.devtools.restart.enabled=false