-- INSERTs gerados automaticamente do Dicionário Tupi-Guarani
-- Total de palavras: 323

INSERT INTO palavras (palavra, significado) VALUES ('Aaru', 'Espécie de bolo preparado com um tatu moqueado, triturado em pilão e misturado com farinha de');
INSERT INTO palavras (palavra, significado) VALUES ('Abá', 'avá - auá - ava - aba - homem - gente - pessoa - ser humano - índio.');
INSERT INTO palavras (palavra, significado) VALUES ('Ababá', 'tribo indígena tupi-guarani que habitava as cabeceiras do rio Corumbiara (MT).');
INSERT INTO palavras (palavra, significado) VALUES ('Abacataia', 'peixe de água salgada, parecido com o peixe-galo - abacutaia - abacatuaia.');
INSERT INTO palavras (palavra, significado) VALUES ('Abaçaí', 'pessoa que espreita, persegue - gênio perseguidor de índios - espírito maligno que perseguia os');
INSERT INTO palavras (palavra, significado) VALUES ('Abacatina', 'aracangüira - abacataia - peixe de água salgada, parecido com o peixe-galo. Abacatuaia:');
INSERT INTO palavras (palavra, significado) VALUES ('Abacatuia', 'aracangüira - abacataia.');
INSERT INTO palavras (palavra, significado) VALUES ('Abaetê', 'pessoa boa - pessoa de palavra - pessoa honrada - abaeté.');
INSERT INTO palavras (palavra, significado) VALUES ('Abaetetuba', 'lugar cheio de gente boa');
INSERT INTO palavras (palavra, significado) VALUES ('Abaité', 'gente ruim - gente repulsiva - gente estranha.');
INSERT INTO palavras (palavra, significado) VALUES ('Abanã', '(gente de) cabelo forte ou cabelo duro.');
INSERT INTO palavras (palavra, significado) VALUES ('Abanheém', 'awañene - língua de gente - a língua que as pessoas falam');
INSERT INTO palavras (palavra, significado) VALUES ('Abaquar', 'senhor (chefe)do vôo - abequar - homem que voa (aba - ara - jabaquara - iabaquara).');
INSERT INTO palavras (palavra, significado) VALUES ('Abaré', 'amigo -(aba - ré - rê - abaruna).');
INSERT INTO palavras (palavra, significado) VALUES ('Abaruna', 'amigo de roupa preta - padre de batina preta - amigo preto - (abuna).');
INSERT INTO palavras (palavra, significado) VALUES ('Abequar', '- senhor (chefe)do vôo - abaquar.');
INSERT INTO palavras (palavra, significado) VALUES ('Abati', 'milho - cabelos dourados - louro.');
INSERT INTO palavras (palavra, significado) VALUES ('Abuna', 'abaruna - padre de batina preta.');
INSERT INTO palavras (palavra, significado) VALUES ('Açaí', 'yasaí - fruta que chora - fruta de onde sai líquido - coquinho pequeno amarronzado, que dá em');
INSERT INTO palavras (palavra, significado) VALUES ('Acag', 'cabeça - (jaguaracambé).');
INSERT INTO palavras (palavra, significado) VALUES ('Acamim', 'uma das espécies de pássaros; uma das espécies de vegetais (iacamim, jacamin).');
INSERT INTO palavras (palavra, significado) VALUES ('Acará', 'garça, ave branca (acaraú).');
INSERT INTO palavras (palavra, significado) VALUES ('Acaraú', 'acaraí, acará, rio das garças (i, acará, ara) (diz-se que a grafia com a letra u, com o som de i');
INSERT INTO palavras (palavra, significado) VALUES ('Acemira', 'acir, o que faz doer, o que é doloroso (moacir).');
INSERT INTO palavras (palavra, significado) VALUES ('Açu', 'grande, considerável, comprido, longo (ant.: mirim) (iguaçu, paraguaçu).');
INSERT INTO palavras (palavra, significado) VALUES ('Aguapé (tupi)', 'awa''pé - redondo e chato, como a vitória-régia - plantas que flutuam em águas calmas -');
INSERT INTO palavras (palavra, significado) VALUES ('Aimara', 'árvore, araçá-do-brejo.');
INSERT INTO palavras (palavra, significado) VALUES ('Aimará', 'túnica de algodão e plumas, usada principalmente pelos guaranis.');
INSERT INTO palavras (palavra, significado) VALUES ('Aimbiré', 'aimoré; amboré.');
INSERT INTO palavras (palavra, significado) VALUES ('Aimirim', 'aimiri, formiguinha.');
INSERT INTO palavras (palavra, significado) VALUES ('Airequecê', 'aamo (xavante) - lua - iaé.');
INSERT INTO palavras (palavra, significado) VALUES ('Airumã', 'estrela-d''alva.');
INSERT INTO palavras (palavra, significado) VALUES ('Airy', 'uma variedade de palmeira.');
INSERT INTO palavras (palavra, significado) VALUES ('Aisó', 'formosa.');
INSERT INTO palavras (palavra, significado) VALUES ('Aiyra', 'filha.');
INSERT INTO palavras (palavra, significado) VALUES ('Ajajá', 'aiaiá - ayayá - colhereiro (espécie de garça, de bico comprido, alargado na ponta e parecido com');
INSERT INTO palavras (palavra, significado) VALUES ('Ajeru', 'ajuru.');
INSERT INTO palavras (palavra, significado) VALUES ('Ajubá', 'amarelo (itajubá).');
INSERT INTO palavras (palavra, significado) VALUES ('Ajuhá', 'fruta com espinho.');
INSERT INTO palavras (palavra, significado) VALUES ('Ajuru', 'ayu''ru - árvore de madeira dura, com frutos de polpa comestível - papagaio - ajeru - jeru - juru.');
INSERT INTO palavras (palavra, significado) VALUES ('Akag', 'cabeça.');
INSERT INTO palavras (palavra, significado) VALUES ('Akitãi', 'baixo , baixa estatura (irakitã - muirakitã).');
INSERT INTO palavras (palavra, significado) VALUES ('Amana', 'amanda, chuva.');
INSERT INTO palavras (palavra, significado) VALUES ('Amanaci', 'amanacy, a mãe da chuva.');
INSERT INTO palavras (palavra, significado) VALUES ('Amanaiara', 'a senhora da chuva ou o senhor da chuva.');
INSERT INTO palavras (palavra, significado) VALUES ('Amanajé', 'mensageiro.');
INSERT INTO palavras (palavra, significado) VALUES ('Amanara', 'dia chuvoso.');
INSERT INTO palavras (palavra, significado) VALUES ('Amanda', 'amana, chuva.');
INSERT INTO palavras (palavra, significado) VALUES ('Amandy', 'dia de chuva.');
INSERT INTO palavras (palavra, significado) VALUES ('Amapá', 'ama''pá - árvore da família das apocináceas (Parahancornia amapa), de madeira útil, e cuja');
INSERT INTO palavras (palavra, significado) VALUES ('Amary', 'uma espécie de árvore.');
INSERT INTO palavras (palavra, significado) VALUES ('Ama-tirí', 'amãtiti, raio, corisco.');
INSERT INTO palavras (palavra, significado) VALUES ('Amboré', 'aimoré.');
INSERT INTO palavras (palavra, significado) VALUES ('Amerê', 'fumaça.');
INSERT INTO palavras (palavra, significado) VALUES ('Ami', 'aranha que não tece teia.');
INSERT INTO palavras (palavra, significado) VALUES ('Anamí', 'uma das espécies de árvores.');
INSERT INTO palavras (palavra, significado) VALUES ('Ananã', 'fruta cheirosa (ananás).');
INSERT INTO palavras (palavra, significado) VALUES ('Anauê', 'salve, olá.');
INSERT INTO palavras (palavra, significado) VALUES ('Anassanduá', 'da mitologia indígena.');
INSERT INTO palavras (palavra, significado) VALUES ('Andira', 'o senhor dos agouros tristes.');
INSERT INTO palavras (palavra, significado) VALUES ('Andirá', 'morcego');
INSERT INTO palavras (palavra, significado) VALUES ('Anhangüera', 'aanhangüera, diabo velho.');
INSERT INTO palavras (palavra, significado) VALUES ('Anhana', 'empurrado - impelido');
INSERT INTO palavras (palavra, significado) VALUES ('Anama', 'grosso, espesso');
INSERT INTO palavras (palavra, significado) VALUES ('Anomatí', 'além, distante');
INSERT INTO palavras (palavra, significado) VALUES ('Antã, atã', 'forte');
INSERT INTO palavras (palavra, significado) VALUES ('Anacê', 'parente');
INSERT INTO palavras (palavra, significado) VALUES ('Anajé', 'gavião de rapina');
INSERT INTO palavras (palavra, significado) VALUES ('Anãmiri', 'anão, duende');
INSERT INTO palavras (palavra, significado) VALUES ('Aondê', 'coruja');
INSERT INTO palavras (palavra, significado) VALUES ('Apicu', 'ape''kü - apicum.');
INSERT INTO palavras (palavra, significado) VALUES ('Ape''kü', 'apicum - mangue - brejo de água salgada (à borda do mar) - apicu - picum - apecum - apecu.');
INSERT INTO palavras (palavra, significado) VALUES ('Apecu', 'ape''kü - coroa de areia feita pelo mar.');
INSERT INTO palavras (palavra, significado) VALUES ('Aapecum', 'ape''kü - apecu.');
INSERT INTO palavras (palavra, significado) VALUES ('Apicu', 'ape''kü - apecu.');
INSERT INTO palavras (palavra, significado) VALUES ('Apicum', 'ape''kü - apicu - apecu - apicum - mangue.');
INSERT INTO palavras (palavra, significado) VALUES ('Apoena', 'aquele que enxerga longe');
INSERT INTO palavras (palavra, significado) VALUES ('Apuama', 'andejo, que não para em casa, veloz, que tem correnteza');
INSERT INTO palavras (palavra, significado) VALUES ('Aquitã', 'curto, pequeno');
INSERT INTO palavras (palavra, significado) VALUES ('Ara', '(de modo geral - com poucas exceções) relativo a aves, às alturas e (mais raramente) àquilo que');
INSERT INTO palavras (palavra, significado) VALUES ('Araçary, arassary', 'variedade de tucano');
INSERT INTO palavras (palavra, significado) VALUES ('Aracê', 'aurora, o nascer do dia, o canto dos pássaros (pela manhã).');
INSERT INTO palavras (palavra, significado) VALUES ('Aracema', 'bando de papagaios (periquitos, jandaias, araras), bando de aves (ara, arara, piracema)');
INSERT INTO palavras (palavra, significado) VALUES ('Aracy', 'a mãe do dia, a fonte do dia, a origem dos pássaros (v. aracê, cy, ara)');
INSERT INTO palavras (palavra, significado) VALUES ('Aram', 'sol');
INSERT INTO palavras (palavra, significado) VALUES ('Arani', 'tempo furioso');
INSERT INTO palavras (palavra, significado) VALUES ('Aracangüira', 'peixe de água salgada, parecido com o peixe-galo - abacataia - abacutaia - abacatuaia -');
INSERT INTO palavras (palavra, significado) VALUES ('Arapuã', 'abelha redonda.');
INSERT INTO palavras (palavra, significado) VALUES ('Arapuca', 'armadilha para aves, consistindo numa pirâmide de gravetos (pequenos paus) superpostos');
INSERT INTO palavras (palavra, significado) VALUES ('Arara', 'jandaia grande, ave grande.');
INSERT INTO palavras (palavra, significado) VALUES ('Araraúna', 'arara preta (arara, una, araruna).');
INSERT INTO palavras (palavra, significado) VALUES ('Ararê', 'amigo dos papagaios');
INSERT INTO palavras (palavra, significado) VALUES ('Araruna', 'araúna, ave preta(araraúna, ara, una, itaúna).');
INSERT INTO palavras (palavra, significado) VALUES ('Aratama, ararama, araruama', 'terra dos papagaios');
INSERT INTO palavras (palavra, significado) VALUES ('Araueté', 'araweté ou araueté, povo de língua da família tupi-guarani, que vive na margem esquerda do');
INSERT INTO palavras (palavra, significado) VALUES ('Araxá', 'lugar alto onde primeiro se avista o sol (segundo definição da cidade Araxá-MG) - lugar alto e');
INSERT INTO palavras (palavra, significado) VALUES ('Assurini', 'tribo pertencente a família lingüística tupi-guarani, localizadas em Trocará, no rio Tocantins,');
INSERT INTO palavras (palavra, significado) VALUES ('Ati', 'gaivota pequena - (atiati).');
INSERT INTO palavras (palavra, significado) VALUES ('Atiati', 'gaivota grande - (ati).');
INSERT INTO palavras (palavra, significado) VALUES ('Auá', 'avá - abá - homem - mulher - gente - índio.');
INSERT INTO palavras (palavra, significado) VALUES ('Auati', 'gente loura - milho - que tem cabelos louros (como o milho) - abati - avati.');
INSERT INTO palavras (palavra, significado) VALUES ('Aauçá', 'uaçá - caranguejo - auçá - guaiá.');
INSERT INTO palavras (palavra, significado) VALUES ('Avá', 'abá, auá, homem, índio.');
INSERT INTO palavras (palavra, significado) VALUES ('avanheenga', 'awañene - língua de gente - a língua que as pessoas falam, ao contrário dos animais - a');
INSERT INTO palavras (palavra, significado) VALUES ('Avaré', 'awa''ré - abaré - amigo - missionário - catequista - (abaruna - abuna).');
INSERT INTO palavras (palavra, significado) VALUES ('Avati', 'gente loura - milho - abati - auati.');
INSERT INTO palavras (palavra, significado) VALUES ('Awañene', 'abanheém - língua de gente - a língua que as pessoas falam, ao contrário dos animais - a');
INSERT INTO palavras (palavra, significado) VALUES ('Awa', 'redondo - ava.');
INSERT INTO palavras (palavra, significado) VALUES ('Awaré', 'avaré.');
INSERT INTO palavras (palavra, significado) VALUES ('Aymberê', 'lagartixa.');
INSERT INTO palavras (palavra, significado) VALUES ('Ayty', 'ninho (parati).');
INSERT INTO palavras (palavra, significado) VALUES ('Ayuru', 'ajuru - árvore de madeira dura, com frutos de polpa comestível.');
INSERT INTO palavras (palavra, significado) VALUES ('bapo', 'maracá - mbaraká - chocalho usado em solenidades - maracaxá - xuatê - cascavel.');
INSERT INTO palavras (palavra, significado) VALUES ('baquara', 'mbaekwara - biquara - sabedor de coisas - esperto - sabido - vivo - (nhambiquara).');
INSERT INTO palavras (palavra, significado) VALUES ('biquara', 'baquara - mbaekwara.');
INSERT INTO palavras (palavra, significado) VALUES ('Caá', 'kaá - mato - folha.');
INSERT INTO palavras (palavra, significado) VALUES ('Caapuã', 'aquele ou aquilo que mora (vive) no mato - caipora - kaapora.');
INSERT INTO palavras (palavra, significado) VALUES ('Caba', 'marimbondo, vespa (v. cacira, laurare)');
INSERT INTO palavras (palavra, significado) VALUES ('Caboclo', 'kariboka - procedente do branco - mestiço de branco com índio - cariboca - carijó - antiga');
INSERT INTO palavras (palavra, significado) VALUES ('Caburé (tupi)', 'kaburé - cafuzo - caboclo - caipira - indivíduo atarracado, achaparrado.');
INSERT INTO palavras (palavra, significado) VALUES ('Cacira', 'vespa de ferroada dolorosa');
INSERT INTO palavras (palavra, significado) VALUES ('caingangue', 'grupo indígena da da região Sul do Brasil, já integrado na sociedade nacional, cuja língua');
INSERT INTO palavras (palavra, significado) VALUES ('Caipora', 'caapora - kaa''pora.');
INSERT INTO palavras (palavra, significado) VALUES ('Camb', 'peito - seio - teta.');
INSERT INTO palavras (palavra, significado) VALUES ('Camé (jê)', 'subtribo do grupo caingangue.');
INSERT INTO palavras (palavra, significado) VALUES ('Camuá', 'palmeira de caule flexível, cheia de pelos espinhosos.');
INSERT INTO palavras (palavra, significado) VALUES ('Camu-camu', 'fruta pouco conhecida que possui grande quantidade de vitamina C, e cuja produção vem');
INSERT INTO palavras (palavra, significado) VALUES ('Canoa', 'embarcação a remo, esculpida no tronco de uma árvore; uma das primeiras palavras indígenas');
INSERT INTO palavras (palavra, significado) VALUES ('Capim', 'caapii - mato fino - folha delgada.');
INSERT INTO palavras (palavra, significado) VALUES ('Carapeba', 'tipo de peixe - acarapeba - acarapeva - acarapéua - (acará - peba).');
INSERT INTO palavras (palavra, significado) VALUES ('Cari', 'o homem branco - a raça branca.');
INSERT INTO palavras (palavra, significado) VALUES ('Cariboca', 'kari''boka - caboclo - procedente do branco - mestiço de branco com índio - curiboca - carijó -');
INSERT INTO palavras (palavra, significado) VALUES ('Carijó', 'procedente do branco - mestiço, como o galináceo de penas salpicadas de branco e preto -');
INSERT INTO palavras (palavra, significado) VALUES ('Carió', 'procedente do branco - caboclo - antiga denominação da tribo indígena guarani, habitante da');
INSERT INTO palavras (palavra, significado) VALUES ('Carioca', 'kari''oka - casa do branco.');
INSERT INTO palavras (palavra, significado) VALUES ('Cuica', 'ku''ika - espécie de rato grande com o rabo muito comprido, semelhante ao canguru - instrumento');
INSERT INTO palavras (palavra, significado) VALUES ('Curiboca', 'caboclo - kari''boka - procedente do branco - mestiço de branco com índio - cariboca - carijó -');
INSERT INTO palavras (palavra, significado) VALUES ('Curumim', 'menino (kurumí).');
INSERT INTO palavras (palavra, significado) VALUES ('Damacuri', 'tribo indígena da Amazônia.');
INSERT INTO palavras (palavra, significado) VALUES ('Damanivá', 'tribo indígena de RR, da região do Caracaraí, Serra Grande e serra do Urubu.');
INSERT INTO palavras (palavra, significado) VALUES ('Deni', 'tribo indígena aruaque, que vive pelos igarapés do vale do rio Cunhuã, entre as desembocaduras');
INSERT INTO palavras (palavra, significado) VALUES ('Eçaí', 'olho pequeno.');
INSERT INTO palavras (palavra, significado) VALUES ('Eçabara', 'o campeador.');
INSERT INTO palavras (palavra, significado) VALUES ('Eçaraia', 'o esquecimento.');
INSERT INTO palavras (palavra, significado) VALUES ('Etê', 'bom - honrado - sincero - eté.');
INSERT INTO palavras (palavra, significado) VALUES ('Galibi', 'tribo indígena da margem esquerda do alto rio Uaçá (AP).');
INSERT INTO palavras (palavra, significado) VALUES ('Geribá', 'nome de um coqueiro.');
INSERT INTO palavras (palavra, significado) VALUES ('Goitacá', 'nômade, errante, aquele que não se fixa em nenhum lugar.');
INSERT INTO palavras (palavra, significado) VALUES ('Guará (i)', 'iguara, ave das águas, pássaro branco de mangues e estuários com grande amplitude de maré');
INSERT INTO palavras (palavra, significado) VALUES ('Guará (2)', 'aguará, aguaraçu, mamífero (lobo) dos cerrados e pampas (açu).');
INSERT INTO palavras (palavra, significado) VALUES ('Guarani(1)', 'raça indígena do interior da América do Sul tropical, habitante desde o Centro Oeste');
INSERT INTO palavras (palavra, significado) VALUES ('Guarani (2)', 'grupo lingüístico pertencente ao grande ramo tupi-guarani, porém mais característico dos');
INSERT INTO palavras (palavra, significado) VALUES ('Guaratinguetá', 'reunião de pássaros brancos.');
INSERT INTO palavras (palavra, significado) VALUES ('Guariní', 'guerreiro, lutador.');
INSERT INTO palavras (palavra, significado) VALUES ('I', 'água - pequeno - fino - delgado - magro');
INSERT INTO palavras (palavra, significado) VALUES ('Iacamim', 'acamim (jacamim).');
INSERT INTO palavras (palavra, significado) VALUES ('Iaé (kamaiurá)', 'lua - aamo (xavante) - airequecê.');
INSERT INTO palavras (palavra, significado) VALUES ('Iandé', 'a constelação Orion.');
INSERT INTO palavras (palavra, significado) VALUES ('Iandê', 'você.');
INSERT INTO palavras (palavra, significado) VALUES ('Iapuçá', 'uma das espécies de macacos (japuçá, jupuçá, jauá, sauá).');
INSERT INTO palavras (palavra, significado) VALUES ('Iba (1)', 'iwa - iua - iva - ruim - feio - imprestável - (paraíba).');
INSERT INTO palavras (palavra, significado) VALUES ('Iiba (2)', 'variação de ubá - madeira - árvore.');
INSERT INTO palavras (palavra, significado) VALUES ('Ibi', 'terra.');
INSERT INTO palavras (palavra, significado) VALUES ('Ibitinga', 'terra branca (tinga).');
INSERT INTO palavras (palavra, significado) VALUES ('Ig', 'água - (i).');
INSERT INTO palavras (palavra, significado) VALUES ('Iguaçu', 'água grande - lago grande - rio grande.');
INSERT INTO palavras (palavra, significado) VALUES ('Indaiá', 'um certo tipo de palmeira');
INSERT INTO palavras (palavra, significado) VALUES ('Ira', 'mel (Iracema, irapuã).');
INSERT INTO palavras (palavra, significado) VALUES ('Iracema', 'lábios de mel (ira, tembé, iratembé).');
INSERT INTO palavras (palavra, significado) VALUES ('Irapuã', 'mel redondo (ira, puã).');
INSERT INTO palavras (palavra, significado) VALUES ('Iratembé', 'lábios de mel (Iracema, ira, tembé).');
INSERT INTO palavras (palavra, significado) VALUES ('Irupé', 'a vitória régia.');
INSERT INTO palavras (palavra, significado) VALUES ('Ita', 'pedra (itaúna).');
INSERT INTO palavras (palavra, significado) VALUES ('Itajubá', 'pedra amarela (ita, ajubá).');
INSERT INTO palavras (palavra, significado) VALUES ('Itatiba', 'muita pedra, abundância de pedras (tiba).');
INSERT INTO palavras (palavra, significado) VALUES ('Itaúna', 'pedra preta (ita, una).');
INSERT INTO palavras (palavra, significado) VALUES ('Ité', 'ruim - repulsivo - feio - repelente - estranho (abaité).');
INSERT INTO palavras (palavra, significado) VALUES ('Iu', 'yu - ju - espinho - (jurumbeba).');
INSERT INTO palavras (palavra, significado) VALUES ('Iua', 'iva - iua - iba - ruim - feio - imprestável - (paraíba).');
INSERT INTO palavras (palavra, significado) VALUES ('Iuçara', 'juçara - jiçara - palmeira que dá palmito.');
INSERT INTO palavras (palavra, significado) VALUES ('Iva', 'iwa - iua - iba - ruim - feio - imprestável - (paraíba).');
INSERT INTO palavras (palavra, significado) VALUES ('Iviturui', '- serro frio; frio na parte mais alta de uma serra.');
INSERT INTO palavras (palavra, significado) VALUES ('Iwa', 'iva - iua - iba - ruim - feio - imprestável - (paraíba).');
INSERT INTO palavras (palavra, significado) VALUES ('Jabaquara', '- rio do senhor do vôo (iabaquara, abequar).');
INSERT INTO palavras (palavra, significado) VALUES ('Jacamim', 'ave ou gênio, pai de muitas estrelas (Yacamim).');
INSERT INTO palavras (palavra, significado) VALUES ('Jaçanã', 'ave que possui as patas sob a forma de nadadeiras, como os patos.');
INSERT INTO palavras (palavra, significado) VALUES ('Jacaúna', 'indivíduo de peito negro.');
INSERT INTO palavras (palavra, significado) VALUES ('Jacu', 'yaku - uma das espécies de aves vegetarianas silvestres, semelhantes às galinhas, perus, faisões,');
INSERT INTO palavras (palavra, significado) VALUES ('Jacuí', 'jacu pequeno.');
INSERT INTO palavras (palavra, significado) VALUES ('Jaguar', 'yawara - cão - lobo - guará.');
INSERT INTO palavras (palavra, significado) VALUES ('Jaguaracambé', 'cão de cabeça branca (ya''wara = cão)+(a''kãg = cabeça)+(peba = branco) - aracambé -');
INSERT INTO palavras (palavra, significado) VALUES ('Japira', 'mel, ira (yapira).');
INSERT INTO palavras (palavra, significado) VALUES ('Japuçá', 'uma das espécies de macacos (iapuçá, jauá, sauá).');
INSERT INTO palavras (palavra, significado) VALUES ('Jauá', 'japuçá (iapuçá, sauá)');
INSERT INTO palavras (palavra, significado) VALUES ('Javaé', 'tribo indígena que habita o interior da ilha do Bananal, aparentada com os carajás, da mesma');
INSERT INTO palavras (palavra, significado) VALUES ('Javari', 'competição cerimonial desportiva religiosa.');
INSERT INTO palavras (palavra, significado) VALUES ('Jé', 'grupo etnográfico a que pertence o grosso dos tapuias - jê - gê.');
INSERT INTO palavras (palavra, significado) VALUES ('Jeru', 'ayu''ru - árvore de madeira dura, com frutos de polpa comestível - papagaio - ajeru - ajuru - juru.');
INSERT INTO palavras (palavra, significado) VALUES ('Ju', 'yu - iu - espinho - (jurumbeba).');
INSERT INTO palavras (palavra, significado) VALUES ('Juçara', 'palmeira fina e alta com um miolo branco, do qual se extrai o palmito, típica da mata atLântica -');
INSERT INTO palavras (palavra, significado) VALUES ('Jumana', 'tribo do grupo aruaque, habitante da região dos rios Japurá e Solimões (amazônia Ocidental) -');
INSERT INTO palavras (palavra, significado) VALUES ('Jumbeba', 'cacto (ou uma espécie de) - jurumbeba - (ju - mbeb).');
INSERT INTO palavras (palavra, significado) VALUES ('Jupuçá', 'iapuçá; japuçá.');
INSERT INTO palavras (palavra, significado) VALUES ('Juru', 'árvore de madeira dura, com frutos de polpa comestível - papagaio - ajeru - jeru - ajuru.');
INSERT INTO palavras (palavra, significado) VALUES ('Jurubatiba', 'lugar cheio de plantas espinhosas (ju - ru - uba -tiba).');
INSERT INTO palavras (palavra, significado) VALUES ('Jurubeba', 'planta (espinhosa) e fruta tida como medicinal (o fruto é, normalmente, verde e perfeitamente');
INSERT INTO palavras (palavra, significado) VALUES ('Jurumbeba', 'folha chata com espinhos - cacto (ou uma espécie de) - jumbeba - (ju - mbeb).');
INSERT INTO palavras (palavra, significado) VALUES ('Kaá', 'caá - mato.');
INSERT INTO palavras (palavra, significado) VALUES ('Kaapora', 'aquilo ou quem vive no mato - caapora - caipora.');
INSERT INTO palavras (palavra, significado) VALUES ('Kabu''ré', 'caburé - cafuzo - caboclo - caipira - indivíduo atarracado, achaparrado.');
INSERT INTO palavras (palavra, significado) VALUES ('Kamby', 'leite - líquido do seio.');
INSERT INTO palavras (palavra, significado) VALUES ('Kaluana', 'lutador de uma lenda da tribo kamaiurá.');
INSERT INTO palavras (palavra, significado) VALUES ('Kamaiurá', 'camaiurá - tribo indígena tupi que vive na região dos formadores do Xingu, entre a lagoa Ipavu');
INSERT INTO palavras (palavra, significado) VALUES ('Karioka', 'carioca - casa do branco.');
INSERT INTO palavras (palavra, significado) VALUES ('Ki''sé', 'faca velha e/ou enferrujada e/ou cheia de dentes e/ou sem cabo - quicé - quicê - quecé - quecê.');
INSERT INTO palavras (palavra, significado) VALUES ('Ku''ika', 'cuica - espécie de rato grande com o rabo muito comprido, semelhante ao canguru - instrumento');
INSERT INTO palavras (palavra, significado) VALUES ('Kurumí', 'menino (curumim)');
INSERT INTO palavras (palavra, significado) VALUES ('Laurare (karajá)', 'marimbondo');
INSERT INTO palavras (palavra, significado) VALUES ('Lauré (pauetê-nanbiquara)', 'arara vermelha');
INSERT INTO palavras (palavra, significado) VALUES ('Macaba', 'fruto da macaúba (comestível - coco de catarro');
INSERT INTO palavras (palavra, significado) VALUES ('Macaúba', 'ma''ká ï''ba - árvore da macaba (fruta do sertão) - macaíba');
INSERT INTO palavras (palavra, significado) VALUES ('Macaíba', 'macaúba');
INSERT INTO palavras (palavra, significado) VALUES ('Manau', 'tribo do ramo aruaque que habitava a região do rio Negro');
INSERT INTO palavras (palavra, significado) VALUES ('Manauara', 'natural de, residente em, ou relativo a Manaus (capital do estado do Amazonas) - manauense');
INSERT INTO palavras (palavra, significado) VALUES ('Mairá', 'uma das espécies de mandioca, típica da região Norte; mandiocaçu; mandioca grande (mandioca,');
INSERT INTO palavras (palavra, significado) VALUES ('Maní', 'deusa da mandioca, amendoim (maniva)');
INSERT INTO palavras (palavra, significado) VALUES ('Manioca', 'mandioca (a deusa Maní, enterrada na própria oca, gerou a raiz alimentícia), (v. mani, oca,');
INSERT INTO palavras (palavra, significado) VALUES ('Maniua', 'maniva');
INSERT INTO palavras (palavra, significado) VALUES ('Maniva', 'tolete ou folha da planta da mandioca; usa-se na alimentação da região Norte, especialmente no');
INSERT INTO palavras (palavra, significado) VALUES ('Mandioca', 'aipim, macaxeira, raiz que é principal alimento dos índios brasileiros (v. manioca)');
INSERT INTO palavras (palavra, significado) VALUES ('Maracá', 'mbaraká - chocalho usado em solenidades - bapo - maracaxá - xuatê - cascavel');
INSERT INTO palavras (palavra, significado) VALUES ('Massau', 'uma das espécies de macaco, pequeno e de rabo comprido, comum na região amazônica -');
INSERT INTO palavras (palavra, significado) VALUES ('Mbaracá', 'maracá - chocalho usado em solenidades - bapo - maracaxá - xuatê - cascavel');
INSERT INTO palavras (palavra, significado) VALUES ('Mbeb', 'chato - achatado - mbeba (jurubeba)');
INSERT INTO palavras (palavra, significado) VALUES ('Membira', 'filho ou filha (v. raira)');
INSERT INTO palavras (palavra, significado) VALUES ('Moponga', 'mu''põga - Pescaria em que se bate na água, com uma vara ou com a mão, para que os peixes');
INSERT INTO palavras (palavra, significado) VALUES ('Motirõ', 'mutirão - reunião para fins de colheita ou construção (ajuda)');
INSERT INTO palavras (palavra, significado) VALUES ('Mu''põga', 'moponga - mupunga - batição');
INSERT INTO palavras (palavra, significado) VALUES ('Mutirão (port/tupi)', 'motirõ');
INSERT INTO palavras (palavra, significado) VALUES ('Nanbiquara', 'fala inteligente, de gente esperta - tribo do Mato Grosso (pauetê-nanbiquara - baquara -');
INSERT INTO palavras (palavra, significado) VALUES ('Nhe', 'nhan - nham - falar - fala - língua');
INSERT INTO palavras (palavra, significado) VALUES ('Nheengatu', 'nhegatu - língua boa - língua fácil de ser entendida (pelos tupis)');
INSERT INTO palavras (palavra, significado) VALUES ('Nhenhenhém', 'nheë nheë ñeñë, falação, falar muito, tagarelice');
INSERT INTO palavras (palavra, significado) VALUES ('oapixana', 'tribo do ramo aruaque do alto rio Branco (RR), nas fronteiras com a Guiana - vapixiana -');
INSERT INTO palavras (palavra, significado) VALUES ('oapina', 'oapixana');
INSERT INTO palavras (palavra, significado) VALUES ('Oca', 'cabana ou palhoça, casa de índio (v. ocara, manioca)');
INSERT INTO palavras (palavra, significado) VALUES ('Ocara', 'praça ou centro de taba, terreiro da aldeia (v. oca, manioca, ocaruçu)');
INSERT INTO palavras (palavra, significado) VALUES ('Ocaruçu', 'praça grande, aumentativo de ocara (v. açu, ocara)');
INSERT INTO palavras (palavra, significado) VALUES ('Pará (1)', 'rio');
INSERT INTO palavras (palavra, significado) VALUES ('Pará (2)', 'prefixo utilizado no nome de diversas plantas');
INSERT INTO palavras (palavra, significado) VALUES ('Paracanã', 'tribo indígena encontrada durante a construçao hidrelétrica de Tucuruí, no rio Tocantins/PA');
INSERT INTO palavras (palavra, significado) VALUES ('Paraíba (1)', 'paraiwa - rio ruim - rio que não se presta à navegação (imprestável) - (para - iba)');
INSERT INTO palavras (palavra, significado) VALUES ('Paraíba (2)', 'parabiwa - madeira inconstante (variada)');
INSERT INTO palavras (palavra, significado) VALUES ('Paraibuna', 'rio escuro e que não serve para navegar');
INSERT INTO palavras (palavra, significado) VALUES ('Paraitunga', 'designação dada aos paracanãs pelos assurinis');
INSERT INTO palavras (palavra, significado) VALUES ('Pauá (tupi)', 'pawa - pava - tudo - muito (no sentido de grande extensão)');
INSERT INTO palavras (palavra, significado) VALUES ('Pauetê-nanbiquara', '- tribo da região do Mato Grosso (nanbiquara, nhambiquara)');
INSERT INTO palavras (palavra, significado) VALUES ('Peba', 'branco - branca - tinga - peva - peua - pewa');
INSERT INTO palavras (palavra, significado) VALUES ('Peua', 'peba');
INSERT INTO palavras (palavra, significado) VALUES ('Peva', 'peba');
INSERT INTO palavras (palavra, significado) VALUES ('Pewa', 'peba');
INSERT INTO palavras (palavra, significado) VALUES ('Picum', 'ape''kü - apecum - mangue - brejo de água salgada');
INSERT INTO palavras (palavra, significado) VALUES ('Piná', 'palmeira fina e alta com um miolo branco, do qual se extrai o palmito, típica da mata atlântica');
INSERT INTO palavras (palavra, significado) VALUES ('Pitiguar', '- potiguar');
INSERT INTO palavras (palavra, significado) VALUES ('Poti', '- camarão, piti (potiguar)');
INSERT INTO palavras (palavra, significado) VALUES ('Potiguar', '- pitiguar, potiguara, pitaguar, indígena da região NE do Brasil');
INSERT INTO palavras (palavra, significado) VALUES ('Puã', '- redondo (irapuã)');
INSERT INTO palavras (palavra, significado) VALUES ('Puca', 'armadilha (arapuca, puçá)');
INSERT INTO palavras (palavra, significado) VALUES ('Puçá', 'armadilha para peixes (e outros animais aquáticos)');
INSERT INTO palavras (palavra, significado) VALUES ('Puçanga', 'mezinha, remédio caseiro (receitado pelos ajés)');
INSERT INTO palavras (palavra, significado) VALUES ('Quecé', 'faca velha e/ou enferrujada e/ou cheia de dentes e/ou sem cabo - ki''sé - quicê - quicé - quecê');
INSERT INTO palavras (palavra, significado) VALUES ('Quibaana', 'tribo da região Norte');
INSERT INTO palavras (palavra, significado) VALUES ('Quicé', 'faca velha e/ou enferrujada e/ou cheia de dentes e/ou sem cabo - ki''sé - quicê - quecé - quecê');
INSERT INTO palavras (palavra, significado) VALUES ('Raira', '- filho (v. membira)');
INSERT INTO palavras (palavra, significado) VALUES ('Ré', '- amigo - rê (geralmente usado como sufixo) (abaré, araré, avaré)');
INSERT INTO palavras (palavra, significado) VALUES ('Rudá', 'deus do amor, para o qual as índias cantavam uma oração ao anoitecer');
INSERT INTO palavras (palavra, significado) VALUES ('Ru', 'folha (jurubeba)');
INSERT INTO palavras (palavra, significado) VALUES ('Sauá', 'uma das espécies de macacos - iapuçá - japuçá - jupuçá - sawá - saá');
INSERT INTO palavras (palavra, significado) VALUES ('Sauim', 'sagüi');
INSERT INTO palavras (palavra, significado) VALUES ('Sawi', 'sagüi');
INSERT INTO palavras (palavra, significado) VALUES ('Surui', 'tribo do parque do Aripuanã, região do Madeira, Rondônia');
INSERT INTO palavras (palavra, significado) VALUES ('Tapuia', 'tapii - tapuio - designação antiga dada pelos tupis aos gentios inimigos - índio bravio - mestiço de');
INSERT INTO palavras (palavra, significado) VALUES ('Tapuio', 'tapii - tapuia - designação antiga dada pelos tupis aos gentios inimigos - índio bravio - mestiço de');
INSERT INTO palavras (palavra, significado) VALUES ('Tembé', 'lábios (Iracema, iratembé)');
INSERT INTO palavras (palavra, significado) VALUES ('Tiba', 'tiwa, tiua, tuba, abundância, cheio');
INSERT INTO palavras (palavra, significado) VALUES ('Tijuca', 'tiyug - líquido podre - lama - charco - pântano - atoleiro - tijuca');
INSERT INTO palavras (palavra, significado) VALUES ('Tijucupaua', 'tiyukopawa - lamaçal - tijucupava');
INSERT INTO palavras (palavra, significado) VALUES ('Timburé', 'uma das espécies de peixes de rio, com manchas e/ou faixas pretas (ximburé, timburê)');
INSERT INTO palavras (palavra, significado) VALUES ('Timburê', 'Timburé (ximburé)');
INSERT INTO palavras (palavra, significado) VALUES ('Tinga', 'branco - branca - peba - (ibitinga)');
INSERT INTO palavras (palavra, significado) VALUES ('Tiririca', 'tiririka - arrastando-se (alastrando-se) - erva daninha famosa pela capacidade de invadir');
INSERT INTO palavras (palavra, significado) VALUES ('Tiyukopauá', 'tijucopaua - lamaçal - tijucupava');
INSERT INTO palavras (palavra, significado) VALUES ('Tiyug', 'tijuca - líquido podre - lama - charco - pântano - atoleiro - tijuca');
INSERT INTO palavras (palavra, significado) VALUES ('Tiwa', 'tiba, tiua, tiba, tuba, abundância, cheio');
INSERT INTO palavras (palavra, significado) VALUES ('Tupi (1)', 'povo indígena que habita(va) o Norte e o Centro do Brasil, até o rio Amazonas e até o litoral');
INSERT INTO palavras (palavra, significado) VALUES ('Tupi (2)', 'um dos principais troncos lingüísticos da América do Sul, pertencente à família tupi-guarani');
INSERT INTO palavras (palavra, significado) VALUES ('Tupi-guarani', 'um das quatro grandes famílias lingüísticas da América do Sul tropical e equatorial;');
INSERT INTO palavras (palavra, significado) VALUES ('Uaçá', 'caranguejo - auçá - guaiá');
INSERT INTO palavras (palavra, significado) VALUES ('Uaçaí', 'açaí - yasaí');
INSERT INTO palavras (palavra, significado) VALUES ('Uaná', 'vagalume (urissanê)');
INSERT INTO palavras (palavra, significado) VALUES ('Uapixana', 'tribo do ramo aruaque do alto rio Branco (RR), nas fronteiras com a Guiana - vapixiana -');
INSERT INTO palavras (palavra, significado) VALUES ('Ubá', 'canoa (geralmente feita de uma só peça de madeira); árvore usada para fazer canoas (canoa)');
INSERT INTO palavras (palavra, significado) VALUES ('Una', 'preto, preta');
INSERT INTO palavras (palavra, significado) VALUES ('Urissanê', 'vagalume (uaná)');
INSERT INTO palavras (palavra, significado) VALUES ('Vapidiana', 'tribo do ramo aruaque do alto rio Branco (RR), nas fronteiras com a Guiana - vapixiana -');
INSERT INTO palavras (palavra, significado) VALUES ('Wapixana', 'tribo do ramo aruaque do alto rio Branco (RR), nas fronteiras com a Guiana - vapixiana -');
INSERT INTO palavras (palavra, significado) VALUES ('Wa''riwa', 'guariba - macaco de coloração escura, barbado. Wasaí: açaí - uaçaí - yasaí');
INSERT INTO palavras (palavra, significado) VALUES ('Xaperu', 'tribo da região Norte');
INSERT INTO palavras (palavra, significado) VALUES ('Xauim', 'uma das espécies de macaco, pequeno e de rabo comprido, comum na região amazônica - sa''wi');
INSERT INTO palavras (palavra, significado) VALUES ('Xavante', 'tribo indígena pertencente à família lingüística jê e que, junto com os xerentes, constitui o maior');
INSERT INTO palavras (palavra, significado) VALUES ('Ximaana', 'tribo habitante da região do rio Javari, na fronteira do Brasil com o Peru');
INSERT INTO palavras (palavra, significado) VALUES ('Ximana', 'tribo do grupo aruaque, habitante da região dos rios Japurá e Solimões (Amazônia Ocidental) -');
INSERT INTO palavras (palavra, significado) VALUES ('Ximburé', 'uma das espécies de peixes de rio (timburé)');
INSERT INTO palavras (palavra, significado) VALUES ('Xoclengue', 'tribo caingangue do Paraná (rio Ivaí)');
INSERT INTO palavras (palavra, significado) VALUES ('Xuatê', 'mbaraká - maracá - chocalho usado em solenidades - bapo - maracaxá - cascavel');
INSERT INTO palavras (palavra, significado) VALUES ('Xumana', 'ximana - jumana');
INSERT INTO palavras (palavra, significado) VALUES ('Xumane', '- ximana.');
INSERT INTO palavras (palavra, significado) VALUES ('Yacamim', 'ave ou gênio; pai de muitas estrelas (jaçamim)');
INSERT INTO palavras (palavra, significado) VALUES ('Yamí (tucano)', 'noite');
INSERT INTO palavras (palavra, significado) VALUES ('Yapira', 'mel (japira)');
INSERT INTO palavras (palavra, significado) VALUES ('Yara', 'deusa das águas - mãe d''água - senhora - iara - lenda da mulher que mora no fundo dos rios');
INSERT INTO palavras (palavra, significado) VALUES ('yasaí', 'açaí - fruta que chora - fronta de onde sai líquido - coquinho pequeno amarronzado, que dá em');
INSERT INTO palavras (palavra, significado) VALUES ('yawara (tupi)', 'jaguar - cão - cachorro - lobo - gato - onça - jaguaracambé.');